ServerEvents.tags('item',event =>{
    //贫瘠花岗岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/poor_granite/aluminum')
    event.add('forge:ores','tfc:ore/poor_granite/aluminum')
    event.add('balm:ores','tfc:ore/poor_granite/aluminum')
    event.add('tfc:ores/aluminum/poor','tfc:ore/poor_granite/aluminum')
    //
    //花岗岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/normal_granite/aluminum')
    event.add('forge:ores','tfc:ore/normal_granite/aluminum')
    event.add('balm:ores','tfc:ore/normal_granite/aluminum')
    event.add('tfc:ores/aluminum/normal','tfc:ore/normal_granite/aluminum')
    //
    //富集花岗岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/rich_granite/aluminum')
    event.add('forge:ores','tfc:ore/rich_granite/aluminum')
    event.add('balm:ores','tfc:ore/rich_granite/aluminum')
    event.add('tfc:ores/aluminum/rich','tfc:ore/rich_granite/aluminum')
    //
    //贫瘠页岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/poor_shale/aluminum')
    event.add('forge:ores','tfc:ore/poor_shale/aluminum')
    event.add('balm:ores','tfc:ore/poor_shale/aluminum')
    event.add('tfc:ores/aluminum/poor','tfc:ore/poor_shale/aluminum')
    //
    //页岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/normal_shale/aluminum')
    event.add('forge:ores','tfc:ore/normal_shale/aluminum')
    event.add('balm:ores','tfc:ore/normal_shale/aluminum')
    event.add('tfc:ores/aluminum/normal','tfc:ore/normal_shale/aluminum')
    //
    //富集页岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/rich_shale/aluminum')
    event.add('forge:ores','tfc:ore/rich_shale/aluminum')
    event.add('balm:ores','tfc:ore/rich_shale/aluminum')
    event.add('tfc:ores/aluminum/rich','tfc:ore/rich_shale/aluminum')
    //
    //贫瘠粘土岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/poor_claystone/aluminum')
    event.add('forge:ores','tfc:ore/poor_claystone/aluminum')
    event.add('balm:ores','tfc:ore/poor_claystone/aluminum')
    event.add('tfc:ores/aluminum/poor','tfc:ore/poor_claystone/aluminum')
    //
    //粘土岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/normal_claystone/aluminum')
    event.add('forge:ores','tfc:ore/normal_claystone/aluminum')
    event.add('balm:ores','tfc:ore/normal_claystone/aluminum')
    event.add('tfc:ores/aluminum/normal','tfc:ore/normal_claystone/aluminum')
    //
    //富集粘土岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/rich_claystone/aluminum')
    event.add('forge:ores','tfc:ore/rich_claystone/aluminum')
    event.add('balm:ores','tfc:ore/rich_claystone/aluminum')
    event.add('tfc:ores/aluminum/rich','tfc:ore/rich_claystone/aluminum')
    //
    //贫瘠石灰岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/poor_limestone/aluminum')
    event.add('forge:ores','tfc:ore/poor_limestone/aluminum')
    event.add('balm:ores','tfc:ore/poor_limestone/aluminum')
    event.add('tfc:ores/aluminum/poor','tfc:ore/poor_limestone/aluminum')
    //
    //石灰岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/normal_limestone/aluminum')
    event.add('forge:ores','tfc:ore/normal_limestone/aluminum')
    event.add('balm:ores','tfc:ore/normal_limestone/aluminum')
    event.add('tfc:ores/aluminum/normal','tfc:ore/normal_limestone/aluminum')
    //
    //富集石灰岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/rich_limestone/aluminum')
    event.add('forge:ores','tfc:ore/rich_limestone/aluminum')
    event.add('balm:ores','tfc:ore/rich_limestone/aluminum')
    event.add('tfc:ores/aluminum/rich','tfc:ore/rich_limestone/aluminum')
    //
    //贫瘠砾岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/poor_conglomerate/aluminum')
    event.add('forge:ores','tfc:ore/poor_conglomerate/aluminum')
    event.add('balm:ores','tfc:ore/poor_conglomerate/aluminum')
    event.add('tfc:ores/aluminum/poor','tfc:ore/poor_conglomerate/aluminum')
    //
    //砾岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/normal_conglomerate/aluminum')
    event.add('forge:ores','tfc:ore/normal_conglomerate/aluminum')
    event.add('balm:ores','tfc:ore/normal_conglomerate/aluminum')
    event.add('tfc:ores/aluminum/normal','tfc:ore/normal_conglomerate/aluminum')
    //
    //富集砾岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/rich_conglomerate/aluminum')
    event.add('forge:ores','tfc:ore/rich_conglomerate/aluminum')
    event.add('balm:ores','tfc:ore/rich_conglomerate/aluminum')
    event.add('tfc:ores/aluminum/rich','tfc:ore/rich_conglomerate/aluminum')
    //
    //贫瘠白云岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/poor_dolomite/aluminum')
    event.add('forge:ores','tfc:ore/poor_dolomite/aluminum')
    event.add('balm:ores','tfc:ore/poor_dolomite/aluminum')
    event.add('tfc:ores/aluminum/poor','tfc:ore/poor_dolomite/aluminum')
    //
    //白云岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/normal_dolomite/aluminum')
    event.add('forge:ores','tfc:ore/normal_dolomite/aluminum')
    event.add('balm:ores','tfc:ore/normal_dolomite/aluminum')
    event.add('tfc:ores/aluminum/normal','tfc:ore/normal_dolomite/aluminum')
    //
    //富集白云岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/rich_dolomite/aluminum')
    event.add('forge:ores','tfc:ore/rich_dolomite/aluminum')
    event.add('balm:ores','tfc:ore/rich_dolomite/aluminum')
    event.add('tfc:ores/aluminum/rich','tfc:ore/rich_dolomite/aluminum')
    //
    //贫瘠硅质岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/poor_chert/aluminum')
    event.add('forge:ores','tfc:ore/poor_chert/aluminum')
    event.add('balm:ores','tfc:ore/poor_chert/aluminum')
    event.add('tfc:ores/aluminum/poor','tfc:ore/poor_chert/aluminum')
    //
    //硅质岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/normal_chert/aluminum')
    event.add('forge:ores','tfc:ore/normal_chert/aluminum')
    event.add('balm:ores','tfc:ore/normal_chert/aluminum')
    event.add('tfc:ores/aluminum/normal','tfc:ore/normal_chert/aluminum')
    //
    //富集硅质岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/rich_chert/aluminum')
    event.add('forge:ores','tfc:ore/rich_chert/aluminum')
    event.add('balm:ores','tfc:ore/rich_chert/aluminum')
    event.add('tfc:ores/aluminum/rich','tfc:ore/rich_chert/aluminum')
    //
    //贫瘠白垩岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/poor_chalk/aluminum')
    event.add('forge:ores','tfc:ore/poor_chalk/aluminum')
    event.add('balm:ores','tfc:ore/poor_chalk/aluminum')
    event.add('tfc:ores/aluminum/poor','tfc:ore/poor_chalk/aluminum')
    //
    //白垩岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/normal_chalk/aluminum')
    event.add('forge:ores','tfc:ore/normal_chalk/aluminum')
    event.add('balm:ores','tfc:ore/normal_chalk/aluminum')
    event.add('tfc:ores/aluminum/normal','tfc:ore/normal_chalk/aluminum')
    //
    //富集白垩岩铝土矿
    event.add('forge:ores/aluminum','tfc:ore/rich_chalk/aluminum')
    event.add('forge:ores','tfc:ore/rich_chalk/aluminum')
    event.add('balm:ores','tfc:ore/rich_chalk/aluminum')
    event.add('tfc:ores/aluminum/rich','tfc:ore/rich_chalk/aluminum')
})